sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

language: php

env:
  global:
    - SYMFONY_VERSION=""
    - deps=""

matrix:
  fast_finish: true
  include:
    - php: 5.3
    - php: 5.3
      env: deps="low"
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: SYMFONY_VERSION="2.3.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.6.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.7.x"
    - php: 5.6
      env: SYMFONY_VERSION="2.8.x-dev"
    - php: 7.0
    - php: hhvm

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:"$SYMFONY_VERSION"; fi

install:
  - if [ "$deps" = "" ]; then composer install; fi
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest; fi

script:
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
